import "@/lib/styles/globals.css";

import type { Metadata } from "next";

import Providers from "./providers";
import { Locale, i18n } from "../../i18n.config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface RootLayoutProps {
  params: Promise<{
    lang: Locale;
  }>;
  children: React.ReactNode;
}

export default async function RootLayout(props: RootLayoutProps) {
  const params = await props.params;
  const { children } = props;

  return (
    <html lang={params.lang}>
      <head>
        <title>TEST APP</title>
      </head>
      <body className="h-full">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
